name: Node-on-push-main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Setup repo
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run coverage
        run: npm run coverage

      - name: Run codecov
        uses: codecov/codecov-action@v1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build docker images using cache
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          registry: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: lastest,${{ steps.tag_version.outputs.new_tag }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
