name: Node-pr-checker

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Setup repo
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run coverage
        run: npm run coverage

      - name: Run codecov
        uses: codecov/codecov-action@v1
